[build]
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[context.production.environment]
API_URL = "staging-mintit-backend.fly.dev"

[context.staging.environment]
API_URL = "staging-mintit-backend.fly.dev"